
export const deckOfCards = {
  'AC': 'Ace of Clubs.png',
  'AD': 'Ace of Diamonds.png',
  'AH': 'Ace of Hearts.png',
  'AS': 'Ace of Spades.png',
  '8C': 'Eight of Clubs.png',
  '8D': 'Eight of Diamonds.png',
  '8H': 'Eight of Hearts.png',
  '8S': 'Eight of Spades.png',
  '5C': 'Five of Clubs.png',
  '5D': 'Five of Diamonds.png',
  '5H': 'Five of Hearts.png',
  '5S': 'Five of Spades.png',
  '4C': 'Four of Clubs.png',
  '4D': 'Four of Diamonds.png',
  '4H': 'Four of Hearts.png',
  '4S': 'Four of Spades.png',
  'JC': 'Jack of Clubs.png',
  'JD': 'Jack of Diamonds.png',
  'JH': 'Jack of Hearts.png',
  'JS': 'Jack of Spades.png',
  'KC': 'King of Clubs.png',
  'KD': 'King of Diamonds.png',
  'KH': 'King of Hearts.png',
  'KS': 'King of Spades.png',
  '9C': 'Nine of Clubs.png',
  '9D': 'Nine of Diamonds.png',
  '9H': 'Nine of Hearts.png',
  '9S': 'Nine of Spades.png',
  'QC': 'Queen of Clubs.png',
  'QD': 'Queen of Diamonds.png',
  'QH': 'Queen of Hearts.png',
  'QS': 'Queen of Spades.png',
  '7C': 'Seven of Clubs.png',
  '7D': 'Seven of Diamonds.png',
  '7H': 'Seven of Hearts.png',
  '7S': 'Seven of Spades.png',
  '6C': 'Six of Clubs.png',
  '6D': 'Six of Diamonds.png',
  '6H': 'Six of Hearts.png',
  '6S': 'Six of Spades.png',
  '10C': 'Ten of Clubs.png',
  '10D': 'Ten of Diamonds.png',
  '10H': 'Ten of Hearts.png',
  '10S': 'Ten of Spades.png',
  '3C': 'Three of Clubs.png',
  '3D': 'Three of Diamonds.png',
  '3H': 'Three of Hearts.png',
  '3S': 'Three of Spades.png',
  '2C': 'Two of Clubs.png',
  '2D': 'Two of Diamonds.png',
  '2H': 'Two of Hearts.png',
  '2S': 'Two of Spades.png',
};

export const hideCard = {
    'D': 'default.png'
}

  
  
